name: Documentation
on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ['*']
    paths:
      - '.github/workflows/docs.yml'
      - 'src/**'
      - 'docs/**'
      - 'Project.toml'
      - 'Manifest.toml'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '.github/workflows/docs.yml'
      - 'src/**'
      - 'docs/**'
      - 'Project.toml'
      - 'Manifest.toml'
jobs:
  Documentation:
    # Run on push's or non-draft PRs
    if: (github.event_name == 'push') || (github.event.pull_request.draft == false)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.6 # earliest supported version
      - uses: actions/cache@v2
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-docs-artifacts-${{ hashFiles('**/Project.toml') }}
          restore-keys: ${{ runner.os }}-docs-artifacts
      - name: Install dependencies
        run: |
          julia --project=docs/ -e 'using Pkg;
              Pkg.develop(PackageSpec(path=pwd()));
              Pkg.instantiate()'
      - uses: julia-actions/julia-docdeploy@releases/v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHON: ""
